# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83ff677b8394802818d518ee36d7ff291a73737a6e7f5ad9f124155148e2fc1004fa3a86dd4b20d23973d8ddaca63c5700e78548cfd0c31023651ea13b425635

  twitter_api_key: aroPJaaUPyefpiKF7hG07PBgc
  twitter_api_secret: FMUghYdYzLjg8uyJfpJHBYpD4ixPyxlQCujLT7615DKQgKuRoq
  # Bearer token used for app authorized requests (using the app limit instead of user limit)
  bearer_token: AAAAAAAAAAAAAAAAAAAAAHUOiwAAAAAABOF4XPi80ShkOV4ZtMVVjao4xEQ%3DwATnFhNqvmvhvV3GkSwA127i2j4i6O9mW3szPvbvjEe1DSBwMe

test:
  secret_key_base: 942911c007cfbb654fc9df38c5d92933a47d72d47876c05877994615faa4dd612c6fbee9931e4279197a7b4465dd3263e2ff9d62de68c773ead01929d19108be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: aroPJaaUPyefpiKF7hG07PBgc
  twitter_api_secret: FMUghYdYzLjg8uyJfpJHBYpD4ixPyxlQCujLT7615DKQgKuRoq
  # Bearer token used for app authorized requests (using the app limit instead of user limit)
  bearer_token: AAAAAAAAAAAAAAAAAAAAAHUOiwAAAAAABOF4XPi80ShkOV4ZtMVVjao4xEQ%3DwATnFhNqvmvhvV3GkSwA127i2j4i6O9mW3szPvbvjEe1DSBwMe
