# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ad0df176a8be66d1bba2b768b562adbfe0dd2b0c65f8a6dd041a451d2292784b00fdaf13dd8a59b4ad5326d74ac69e5381d25505adcfac724bc61514780f59
  twitter_api_key: aroPJaaUPyefpiKF7hG07PBgc
  twitter_api_secret: FMUghYdYzLjg8uyJfpJHBYpD4ixPyxlQCujLT7615DKQgKuRoq
  # Bearer token used for app authorized requests (using the app limit instead of user limit)
  bearer_token: AAAAAAAAAAAAAAAAAAAAAHUOiwAAAAAABOF4XPi80ShkOV4ZtMVVjao4xEQ%3DwATnFhNqvmvhvV3GkSwA127i2j4i6O9mW3szPvbvjEe1DSBwMe

  username: 'provomalone@gmail.com'
  password: 'homalone'

test:
  secret_key_base: e16e168f430f6cd86de15cd25d4f0a9fde271187f76baeb03467b6abdb1b10e9a33f080f6197c16e8e26095342de1051ef1b930927a6e10f4e8ca0d7a6edb529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  username: 'provomalone@gmail.com'
  password: 'homalone'
